[cppyy] Preserve C++ docstring when uninformative PyExceptions/no traceback
This follows up on https://github.com/root-project/root/pull/18163 which broke test `test_fragile:test10_documentation` on the compiler-research forks since we lose a C++ side error.
This patch resolves the issue by preserving C++ errors when that information can be actually useful, either when the PyException is uninformative, or there is no Python traceback.
We completely preserve the intended behaviour of the original commit:

```py
import cppyy

def inner_func(x):
    raise ValueError("hello")

def func(x):
    return inner_func(x)

cpp_wrapper = cppyy.gbl.std.function["double(double)"](func)

cpp_wrapper(3)
```

resulting in something like:

```
Traceback (most recent call last):
  File "/home/ajomy/cppyy-interop-dev/CppInterOp/cppyy/test/test_err.py", line 11, in <module>
    cpp_wrapper(3)
  File "/home/ajomy/cppyy-interop-dev/CppInterOp/cppyy/test/test_err.py", line 7, in func
    return inner_func(x)
           ^^^^^^^^^^^^^
  File "/home/ajomy/cppyy-interop-dev/CppInterOp/cppyy/test/test_err.py", line 4, in inner_func
    raise ValueError("hello")
ValueError: hello
```
instead of also appending `ValueError: double std::function<double(double)>::operator()(double __args) =>
ValueError: hello` to the err message

But also retaining the C++ docstring context in cases as seen in `test_fragile:test10_documentation` where we expect the docstring when calling the following overload:

```cpp
class D {
public:
    virtual int check() { return (int)'D'; }
    virtual int check(int, int) { return (int)'D'; }
    void overload() {}
    void overload(no_such_class*) {}
    void overload(char, int i = 0) {}  // Reflex requires a named arg
    void overload(int, no_such_class* p = 0) {}
};
```

as `d.overload(None)`:

```
    assert "void fragile::D::overload(char, int i = 0)".replace(" ", "") in err_msg
```